[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3000"

# Variables que deben configurarse en Railway dashboard
# DATABASE_URL = "postgresql://..."
# GEMINI_API_KEY = "..."
